version: "3.9"

services:
  db:
    build:
      dockerfile: ./docker/db.Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: db
      MYSQL_PASSWORD: db
      MYSQL_DATABASE: db
    ports:
      - "3306:3306"
  app:
    build:
      dockerfile: ./docker/app.Dockerfile
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: "mariadb+mariadbconnector://db:db@db/db"
    depends_on:
      - db
