name: build

on:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - run: sudo apt-get -y install gcc libmariadb-dev
      - run: pip install poetry
      - run: poetry install
      - run: black --check .
      - run: isort --check .
      - run: flake8 .
      - run: mypy --strict .
